apiVersion: v1
kind: Pod
metadata:
  name: pvc-test-ior
spec:
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
        - matchExpressions:
          - key: topology.kubernetes.io/region
            operator: In
            values:
            - us-west
            - us-east
          - key: nvidia.com/gpu.product
            operator: In
            values:
            - NVIDIA-A100-SXM4-80GB
            - NVIDIA-A10
  containers:
  - name: test
    image: unlhcc/alphafold:2.3.2
    command: ["/bin/bash", "-c"]
    args:
        - >-
            cd /data;
            mkdir bfd;
            cp /alphadata/bfd/*index bfd/;
            cp /alphadata/bfd/bfd_metaclust_clu_complete_id30_c90_final_seq.sorted_opt_cs219.ffdata bfd/;
            cp /alphadata/bfd/bfd_metaclust_clu_complete_id30_c90_final_seq.sorted_opt_hhm.ffdata bfd/;
            cd bfd ;
            ln -s /alphadata/bfd/bfd_metaclust_clu_complete_id30_c90_final_seq.sorted_opt_a3m.ffdata;
            cd ../ ;
            cp /alphadata/examples/input.fasta .;
            /app/run_alphafold.sh --fasta_paths=input.fasta --output_dir=output_directory  --model_preset=monomer  --max_template_date=2023-10-10  --data_dir=/alphadata  --use_gpu_relax  --db_preset=full_dbs  --uniref90_database_path=/alphadata/uniref90/uniref90.fasta  --mgnify_database_path=/alphadata/mgnify/mgy_clusters_2022_05.fa  --bfd_database_path=/data/bfd/bfd_metaclust_clu_complete_id30_c90_final_seq.sorted_opt  --template_mmcif_dir=/alphadata/pdb_mmcif/mmcif_files  --obsolete_pdbs_path=/alphadata/pdb_mmcif/obsolete.dat  --uniref30_database_path=/alphadata/uniref30/UniRef30_2021_03  --pdb70_database_path=/alphadata/pdb70/pdb70;
            tar -cvf /alphadata/examples/output.tar output_directory;
    resources:
      limits:
        memory: 128Gi
        nvidia.com/gpu: "1"
        cpu: "8"
        ephemeral-storage: 500Gi
      requests:
        memory: 128Gi
        nvidia.com/gpu: "1"
        cpu: "8"
        ephemeral-storage: 500Gi
    volumeMounts:
        - mountPath: /alphadata
          name: alphadata
        - mountPath: /data
          name: scratch
  restartPolicy: Never
  volumes:
     - name: alphadata
       persistentVolumeClaim:
         claimName: alphadata
     - name: scratch
       emptyDir: {}
